Repository jaychang99/tadak-frontend, pull requests merged in 2022-11, with the labels that each got.

#16 REACT_APP_API_ENDPOINT 를 https:/./api.tadak.dev/ 로 변경
  .env
Labels: chore

#15 input 컴포넌트 console.log 버그 처리
  src/components/common/Inputs/InputEmail/index.js
  src/components/common/Inputs/InputPassword/index.js
  src/components/common/Inputs/InputPasswordAndCheck/index.js
  src/components/common/Inputs/InputUserName/index.js
Labels: bug

#17 (임시로) 서비스명을 ttdtt 에서 TADAK 으로 통일하는 작업
  Dockerfile
  package-lock.json
  package.json
  src/components/common/Breadcrumb/index.js
  src/components/common/NavBar/index.js
Labels: feature, chore

#24 Feature #11 modal issues
  .env
  src/components/LanguageCard/styles.js
  src/components/PortalModal/index.js
  src/components/PortalModal/styles.js
  src/components/Timer/index.js
  src/components/Timer/styles.js
  src/components/TypeInput/index.js
  src/components/common/styles.js
  src/pages/Login/index.js
  src/pages/Main/styles.js
  src/pages/Register/index.js
  src/styles/motions/motions.js
Labels: feature
